name: FlatRockBuild

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'gradle'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > $GITHUB_WORKSPACE/local.properties
             echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_WORKSPACE/local.properties
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Run tests
        run: ./gradlew test

      - name: Locate APK
        id: locate-apk
        run: echo "APK_PATH=$(find app/build/outputs/apk/release -name *.apk | head -n 1)" >> $GITHUB_ENV

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: 'alpha'
          file: ${{ env.APK_PATH }}
