name: FlatRockBuild
on:
   pull_request:
      branches: [ main ]
   push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
                  java-version: 1.8
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
             node-version: '16'
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Run tests
        run: ./gradlew test

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          path: app/build/outputs/apk/debug/app-debug.apk



