name: FlatRockBuild
on:
   pull_request:
      branches: [ main ]
   push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
         node-version: '20 '
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '18'
            cache: 'gradle'

      - name: Run tests
        run: ./gradlew test
      - name: Locate APK
        id: locate-apk
        run: echo "APK_PATH=$(find app/build/outputs/apk/debug/ -name *.apk | head -n 1)" >> $GITHUB_ENV
      - name: Build with Gradle
        run: ./gradlew assembleRelease



      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: 'alpha'
          path: ${{ env.APK_PATH }}



