name: FlatRockBuild
on:
   pull_request:
      branches: [ main ]
   push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
                - name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                  node-version: '16'
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '18'
            cache: 'gradle'


      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Run tests
        run: ./gradlew test

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: 'alpha'
          path: app/build/outputs/apk/debug/app-debug.apk



